export { default as Login } from "./Login"
export { default as Register } from "./Register"
export { default as Home } from "./Home"
export { default as Dashboard } from "./Dashboard"
export { default as Elections } from "./Elections"
export { default as Verification } from "./Verification"
export { default as Positions } from "./Positions"
export { default as Candidates } from "./Candidates"
export { default as Voters } from "./Voters"
export { default as NotFoundPage } from "./NotFoundPage"

