export { default as Navbar } from "./Navbar"
export { default as Footer } from "./Footer"
export { default as Hero } from "./Hero"
export { default as Pricing } from "./Pricing"
export { default as Features } from "./Features"
export { default as Testimonials } from "./Testimonials"
export { default as Contact } from "./Contact"
export { default as Sidebar } from "./Sidebar"
